apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - users-service.yaml
  - users-configmap.yaml
  - users-secret.yaml
  - users-deployment.yaml
images:
- name: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/users
  newName: 375586205616.dkr.ecr.ap-northeast-2.amazonaws.com/users
  newTag: v1.0.1